version: '3.9'

services:

  postgres:
    image: postgres:16.1
    container_name: postgres_cats
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - .env
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cats

  redis:
    image: redis:7.2.4
    container_name: redis_cats
    ports:
      - $REDIS_PORT:$REDIS_PORT
    restart: always
    volumes:
      - redis_data:/data
    command: redis-server --port $REDIS_PORT --requirepass $REDIS_PASS --maxmemory 250mb
    networks:
      - cats

  backend:
    image: backend_image_cats
    build: 
      context: .
    container_name: backend_cats
    command: 
      bash "scripts/backend_app.sh"
    ports:
      - $BACKEND_PORT:$BACKEND_PORT
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    restart: always
    volumes:
      - backend_data:/backend_app/static/media
    networks:
      - cats

networks:
  cats:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  backend_data:
  