version: '3.8'

services:

  postgres:
    image: postgres:latest
    container_name: postgres_cats
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - .env
    restart: always
    volumes:
      - postgres-data-cats:/var/lib/postgresql/data
    networks:
      - backend-cats

  backend_app:
    image: backend_app_image_cats
    container_name: backend_app_cats
    build:
      context: .
    command: 
      bash "scripts/backend_app.sh"
    ports:
      - $BACKEND_PORT:$BACKEND_PORT
    env_file:
      - .env
    depends_on:
      - postgres
      # - redis
    restart: always
    volumes:
      - ./static/media:/backend_app/static/media
    networks:
      - backend-cats

  redis:
    container_name: redis_cats
    image: redis:7.2.3
    restart: always
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    expose:
      - ${REDIS_PORT}
    command:
      - redis-server
      - --port ${REDIS_PORT}
      - --requirepass ${REDIS_PASS}
      - --maxmemory 100mb
    networks:
      - backend-cats

networks:
  backend-cats:
    driver: bridge

volumes:
  postgres-data-cats:
  backend_app-data:
